### ISSUE TITLE
Пример для БД?

### ISSUE THREAD

**Issue by ghost** [Haran/Mail.CONF#1]
Привет!
Использовал ваш мануал из статьи на хабре
Очень понравился, однако остался простой, но очень важный вопрос...
Вы предоставили дамп структуры БД, но как ПРАВИЛЬНО вводить туда данные я понятия не имею. Postfixadmin не устанавливал.

Не могли бы вы привести примеры? Хотя-бы для таблицы mailbox, ибо свеженастроенный почтовый сервер даже не на чем проверить.

Спасибо :)

**Comment by Haran** [comment]
Приветствую.

Для начала нужны домены:

```
INSERT INTO `domain` (`domain`, `description`, `aliases`, `mailboxes`, `maxquota`, `quota`, `transport`, `backupmx`, `created`, `modified`, `active`) VALUES
('ALL', '', 0, 0, 0, 0, '', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1),
('domain.tld', 'Наш домен', 0, 0, 0, 0, 'virtual', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1);
```

Для того, чтобы заработали просто почтовые ящики нужно вносить данные в таблицы `mailbox` и `alias`. Вставляем в mailbox, устанавливая нужный нам хэш пароля (кодируем его в md5crypt, если шли по мануалу, но, кстати, лучше изменить на что-то более надёжное - md5crypt более не котируется).

```
INSERT INTO `mailbox` (`username`, `password`, `name`, `maildir`, `quota`, `local_part`, `domain`, `created`, `modified`, `active`, `accessed`, `accesstype`, `accessip`, `permanent`, `advert`) VALUES
('username@domain.tld', 'Здесь должен быть хэш', 'реальное имя пользователя', 'username@domain.tld/', 204800000, 'username', 'domain.tld', '2014-10-09 00:00:00', '2014-10-09 00:00:00', 1, '0000-00-00 00:00:00', 'IMAP', '127.0.0.1', 0, 1);
```

И транспорт:

```
INSERT INTO `alias` (`address`, `goto`, `domain`, `created`, `modified`, `active`) VALUES
('username@domain.tld', 'username@domain.tld', 'domain.tld', '2013-10-06 23:52:11', '2013-10-06 23:52:11', 1);
```

Как видите, чтобы не корячиться в командной строке, нужен интерфейс. У нас самописный, на отдельном сервере, который с мейлом общается по RESTful, но для внутреннего использования может подойти и postfixadmin.

**Comment by ghost** [comment]
Благодарю вас за подробный ответ!
Не могли бы вы уделить мне еще немного времени?

Есть несколько ньюансов:
1) Зачем вносить "ALL" в список доменов?
Я подозреваю, что из-за этой записи postfix выдает такую ошибку:

> Oct  9 16:34:40 xdevelnetinc postfix/submission/smtpd[17315]: warning: non-null host address bits in "127.0.0.1/8", perhaps you should use "127.0.0.0/8" instead

2)

> Для того, чтобы заработали просто почтовые ящики нужно вносить данные в таблицы mailbox и alias.

Я вообще не вижу логики в этой записи/этом действии. Разве alias не созданы, чтобы объединять имена почтовых ящиков в один? Т.е. как симлинк? Если нет, то получается, что address и goto всегда будут тождественны.

3) Я привык к командной строке, всегда использую её и только её для администрирования без всякого дискомфорта. А для обычных пользователей я, вероятно, напишу web interface - благо, опыт и знания позволяют.

Однако, судя по структуре таблиц, я сделал 2 вывода:
а) некоторые таблицы не используются непосредственно postfix/dovecot2
б) некоторые поля в используемых таблицах не используются postfix/dovecot2
Т.е. предоставленный вами дамп структуры есть некая заготовка под web interface администрирования/etc. Если у вас есть возможность, сообщите какие поля/таблицы я могу изъять из БД, т.к., опять таки, интерфейс буду писать свой. Я буду крайне признателен вам :)

P.S.
1) Использую FreeBSD. Почтовую систему строил на основе вашей статьи с OS-specific изменениями
2) Если вы позволите - могу ли я использовать вашу статью как основу для новой статьи(с исправлениями/дополнениями/etc.)?

С ув. Xdevelnet

**Comment by Haran** [comment]
Отвечу не по порядку, а за что глаз зацепится.

127.0.0.1/8, вероятно, не нравится из-за некорректности записи. 127.0.0.1/8 не может являться адресом подсети (постфикс подсказывает 127.0.0.0/8 как корректную запись). Если указывается именно 127.0.0.1, то CIDR маска должна быть 127.0.0.1/32.

Alias сам на себя - это задел для использования функционала vacation (плагин sieve) с опцией "store and forward" и catchall алиасов для некоторых доменов. Если ни то, ни другое использовать не собираетесь, такой алиас можно не добавлять. 
Postfixadmin предусматривает эти случаи, поэтому по умолчанию такой алиас и появляется. Оттуда же и таблицa vacation и иже с ней. Изначально в статье всего этого не было предусмотрено, чтобы излишне не перегружать материал - я рассчитывал именно на заполнение БД из postfixadmin.

Домен ALL потребуется, если используются domain alias. Например, у меня название первичного домена имеет омоним (dautkom.lv ~ dautcom.lv). И чтобы почта не терялась, был сделан domain alias. Без этой записи он не отработает. И опять же, postfixadmin эту штуку берёт на себя. Если такой функционал не будете использовать, можно эту запись не добавлять.

Базу данных я существенно модифицировал в процессе миграции и создания веб-интерфейса:
- http://pastebin.com/XQTqnKc9 первичная структура
- http://pastebin.com/yuyyTq5G если нужен sieve vacation и/или fetchmail 
- http://pastebin.com/nUAMKUnQ если нужен алиас сам на себя, чтобы не сгружать это на интерфейс я использую триггер. FK тут не подойдёт, потому что будут orphan алиасы.

Материал для своей статьи можете смело использовать, к собственноручно написанным материалам я отношусь, как к public domain. Единственная просьба, откажитесь от md5crypt в пользу чего-нибудь более секьюрного SHA512 или SHA256. 
Также неплохо было бы обновить информацию по защите от переборов. Как бы fail2ban ни ругали, свою работу он выполняет. Я бы упомянул возможность incremental банов, как в http://habrahabr.ru/post/238303/, потому что могу подтвердить - бот-сети поумнели в плане перебора и работают хорошо, мне даже к неудовольствию многих пришлось ужесточить требования к сложности пароля.

**Comment by ghost** [comment]
> 127.0.0.1/8, вероятно, не нравится из-за некорректности записи

вся проблема в том, что самой записи нет
Все закомментировано. Откуда оно берет 127.0.0.1 неясно... Даже при удаленной строке с ALL.

В общем, буду разбираться. Спасибо вам ;)

**Comment by ghost** [comment]
Да, вы правы, там есть над чем поработать
Кроме того, есть совершенно не описанный аспект о сертификатах. Все клиенты ругаются на самоподписанные сертификаты, Thunderbird отказывается логиниться даже если подтвердить исключение. А без шифрования как-то стремно.
Решение проблемы с сертификатами я уже нашел, но еще не реализовал.

В будущем, если вам интересно, конечно, скину ссылку на работу.

**Comment by Haran** [comment]
Буду благодарен за ссылку. Другой взгляд на знакомые вещи зачастую открывает их с неожиданной стороны. С большим интересом почитаю. 

P.S. 127.0.0.1/8 посмотрите в mynetworks, в postconf -f, в debug_peer_list и т.п.
